### ISSUE TITLE
Outdated qunit version

### ISSUE THREAD

**Issue by olegabr** [kof/node-qunit#110]
The current qunit release is https://github.com/jquery/qunit/releases/tag/1.16.0
it is different from the used 1.10.0 version here.
The testAsync API has changed in particular: http://api.qunitjs.com/QUnit.asyncTest/
Now node-qunit forces me to use the deprecated style.

**Comment by nikolas** [comment]
I tried to updating to just qunit 1.11.0, in an attempt to introduce as minimal a change as possible, but it was unclear to me how to fix the errors that arose. Maybe I'll try again soon.

**Comment by monolithed** [comment]
It seems the project is dead. I moved to Mocha (

```
npm WARN engine qunit@0.7.7: wanted: {"node":">=0.6.0 < 5.0"} (current: {"node":"5.3.0","npm":"3.3.12"})
```

**Comment by leobalter** [comment]
@monolithed good luck! As long as you're writing tests for your software, that's great!

This project indeed needs some care, I wish I could have more available time, but that's not happening. Even though, the core of QUnit (`qunitjs` on npm) is still in active development and can be used with node applied to other reporter module as `qunit-tap`. I have plans to look after QUnit on the cli after I'm able to release QUnit 2.0.
