### ISSUE TITLE
Warning for Node 6

### ISSUE THREAD

**Issue by Krinkle** [kof/node-qunit#133]
> 01:26:39 npm WARN engine qunit@0.9.1: wanted: {"node":">=0.6.0 < 5.0"} (current: {"node":"6.9.1","npm":..})

**Comment by kof** [comment]
Please send me a pr if you verified that it works on node 6.

**Comment by kof** [comment]
or actually as you are collaborator, just merge and publish!

**Comment by Krinkle** [comment]
Thanks. Yeah, it seems to work fine on Node 6.
